// Copyright (c) 2024 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-layout: guide-multipane
:projectid: jakarta-data
:page-duration: 500 minutes
:page-releasedate: 2024-01-01
:page-majorupdateddate: 2023-01-01
:page-description: Description - TODO
:page-tags: ['jakarta-ee']
:page-related-guides: []
:page-permalink: /guides/{projectid}
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/prod
:source-highlighter: prettify
:page-seo-title: Jakarta Data - TODO
:page-seo-description: Jakarta Data - TODO
:guide-author: Open Liberty
= Data Persistence with Jakarta Data
[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

== What you'll learn

=== Intro
TODO

=== What is Jakarta Data?
TODO

[role='command']
include::{common-includes}/gitclone.adoc[]


== Creating an Entity and Repository

In Jakarta Data an entity defines the structure for persisting a piece of data. This structure is represented by a Java object and it's associated fields. Start by creating a simple record class.

[role="code_command hotspot file=0", subs="quotes"]
----
#Create the `Package` class.#
`src/main/java/io/openliberty/guides/data/Package.java`
----

Package.java
[source, Java, linenums, role='code_column hide_tags=copyright,app-only']
----
include::finish/src/main/java/io/openliberty/guides/data/Package.java[]
----

This is a simple entity, with a few fields. 

//TODO Packages or PackageRepository?
[role="code_command hotspot file=1", subs="quotes"]
----
#Create the `Packages.java` class.#
`src/main/java/io/openliberty/guides/data/Packages.java`
----

Packages.java
[source, Java, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/main/java/io/openliberty/guides/data/Packages.java[]
----

Repositories in Jakarta Data provide a simplified means for interacting with persistent data. Jakarta Data provides several built in Repositories with common methods which can be extended. The [hotspot=CrudRepository file=1]`CrudRepository` interface provides methods for Create, Read, Update, and Delete (CRUD) operations.

----
#Create the `Packages.java` class.#
`src/main/java/io/openliberty/guides/data/Packages.java`
----
Packages.java
[source, Java, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/main/java/io/openliberty/guides/data/Packages.java[]
----



----
#Create the `Packages.java` class.#
`src/main/java/io/openliberty/guides/data/Packages.java`
----
Packages.java
[source, Java, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/main/java/io/openliberty/guides/data/Packages.java[]
----

== Using Annotations

----
#Create the `Packages.java` class.#
`src/main/java/io/openliberty/guides/data/Packages.java`
----
Packages.java
[source, Java, linenums, role='code_column']
----
include::finish/src/main/java/io/openliberty/guides/data/Packages.java[]
----

=== `@Find` and `@By`



=== Renaming provided methods
`@Insert`


== Query by Method Name




== Sort, Limit, and Paging



== Query Annotations