// Copyright (c) 2024 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-layout: guide-multipane
:projectid: jakarta-data
:page-duration: 500 minutes
:page-releasedate: 2024-01-01
:page-majorupdateddate: 2023-01-01
:page-description: Description - TODO
:page-tags: ['']
:page-related-guides: ['', ']
:page-permalink: /guides/{projectid}
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/prod
:source-highlighter: prettify
:page-seo-title: Jakarta Data - TODO
:page-seo-description: Jakarta Data - TODO
:guide-author: Open Liberty
= Data Persistence with Jakarta Data
[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

== What you'll learn

=== Intro
TODO

=== What is Jakarta Data?
TODO

[role='command']
include::{common-includes}/gitclone.adoc[]


== Creating an Entity and Repository

In Jakarta Data an entity defines the structure for persisting a piece of data. This structure is represented by a Java object and it's associated fields. Start by creating a simple record class.

[role="code_command hotspot", subs="quotes"]
----
#Create the `Package` class.#
`src/main/java/io/openliberty/guides/data/Package.java`
----

This is a very simple entity, with only a single field `id`.

Repositories in Jakarta Data provide a simplified means for interacting with persistent data. Jakarta Data provides several built in Repositories with common methods which can be extended. The `CrudRepository` interface provides methods for Create, Read, Update, and Delete (CRUD) operations.

//TODO Packages or PackageRepository?
----
#Create the `Packages.java` class.#
`src/main/java/io/openliberty/guides/data/Packages.java`
----
Packages.java
[source, Java, linenums, role='code_column hide_tags=query-by-method-step3,query-by-method-step2']
----
include::finish/src/main/java/io/openliberty/guides/data/Packages.java[]
----

With some text

another paragraph

some additional writing here

really get this spaced out

=== Maybe something else here

With some text

another paragraph

some additional writing here

really get this spaced out

----
#Create the `Packages.java` class.#
`src/main/java/io/openliberty/guides/data/Packages.java`
----
Packages.java
[source, Java, linenums, role='code_column hide_tags=query-by-method-step3,query-by-method-step1']
----
include::finish/src/main/java/io/openliberty/guides/data/Packages.java[]
----

=== Another Section
With some text

another paragraph

some additional writing here

really get this spaced out


----
#Create the `Packages.java` class.#
`src/main/java/io/openliberty/guides/data/Packages.java`
----
Packages.java
[source, Java, linenums, role='code_column hide_tags=query-by-method-step1']
----
include::finish/src/main/java/io/openliberty/guides/data/Packages.java[]
----
//To use this configuration property,
//[role="code_command hotspot file=3", subs="quotes"]
//----
//#Create the `InventoryConfig.java` class.#
//`src/main/java/io/openliberty/guides/inventory/InventoryConfig.java`
//----
//InventoryConfig.java
//[source, Java, linenums, role='code_column hide_tags=copyright,inject-inMaintenance,custom-converter,isInMaintenance,getEmail']
//----
//include::finish/src/main/java/io/openliberty/guides/inventory/InventoryConfig.java[]
//----

=== One more section
Use this to add some space?

spacing things out more

== Using Annotations

With some text

another paragraph

some additional writing here

really get this spaced out

With some text

another paragraph

some additional writing here

really get this spaced out


== Query by Method Name

With some text

another paragraph

some additional writing here

really get this spaced out

With some text

another paragraph

some additional writing here

really get this spaced out



== Sort, Limit, and Paging

With some text

another paragraph

some additional writing here

really get this spaced out

With some text

another paragraph

some additional writing here

really get this spaced out



== Query Annotations